// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSumMwljuTgMPorgu-tCCQ1Nq3JNBlf9g',
    appId: '1:1024206594957:web:58306d5a416382d6f2d3c4',
    messagingSenderId: '1024206594957',
    projectId: 'good-omens-65f54',
    authDomain: 'good-omens-65f54.firebaseapp.com',
    storageBucket: 'good-omens-65f54.appspot.com',
    measurementId: 'G-8ESQFZFVFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3_SysQ9RlNK5Rxwr1943FPIM1CO_xSYs',
    appId: '1:1024206594957:android:fd543af86453f1c3f2d3c4',
    messagingSenderId: '1024206594957',
    projectId: 'good-omens-65f54',
    storageBucket: 'good-omens-65f54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3gbOkMJ3MKGBGcJuT0P0aEB_1oBysM2o',
    appId: '1:1024206594957:ios:d438cc1ef1351faaf2d3c4',
    messagingSenderId: '1024206594957',
    projectId: 'good-omens-65f54',
    storageBucket: 'good-omens-65f54.appspot.com',
    iosBundleId: 'com.example.goodOmens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3gbOkMJ3MKGBGcJuT0P0aEB_1oBysM2o',
    appId: '1:1024206594957:ios:d438cc1ef1351faaf2d3c4',
    messagingSenderId: '1024206594957',
    projectId: 'good-omens-65f54',
    storageBucket: 'good-omens-65f54.appspot.com',
    iosBundleId: 'com.example.goodOmens',
  );
}
